# Generated by Django 2.0.6 on 2019-03-12 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relateditemsmodel',
            name='itemForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiApp.UserLoginModel'),
        ),
    ]
