# Generated by Django 2.0.6 on 2019-03-13 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0002_relateditemsmodel_itemforeignkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='image',
            new_name='post_Image',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='text',
            new_name='post_Text',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='title_Post',
            new_name='post_Title',
        ),
        migrations.RenameField(
            model_name='relateditemsmodel',
            old_name='logo',
            new_name='item_Image',
        ),
        migrations.RenameField(
            model_name='relateditemsmodel',
            old_name='some_text',
            new_name='item_Text',
        ),
        migrations.RenameField(
            model_name='relateditemsmodel',
            old_name='title_Item',
            new_name='item_Title',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='createdDateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='updatedDateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='relateditemsmodel',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relateditemsmodel',
            name='updated_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
