# Generated by Django 2.0.6 on 2019-03-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0004_auto_20190313_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_Image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='item_Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
