# Generated by Django 2.0.6 on 2019-03-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0005_auto_20190313_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_Image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='item_Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
