# Generated by Django 2.0.6 on 2019-03-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0009_auto_20190313_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='itemForeignKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikiApp.PostModel'),
        ),
    ]
