# Generated by Django 2.0.6 on 2019-03-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiApp', '0010_auto_20190313_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relateditemsmodel',
            name='item_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
